// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwHSqNFuSYHKPMd-JAUsIplPtcSioHm3k',
    appId: '1:777032316980:web:04649a2647db43d7573261',
    messagingSenderId: '777032316980',
    projectId: 'chatly-11c65',
    authDomain: 'chatly-11c65.firebaseapp.com',
    storageBucket: 'chatly-11c65.firebasestorage.app',
    measurementId: 'G-0FS733X42P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZc403-L-VSi--F2lK8EPtCjA5cyVfr6A',
    appId: '1:777032316980:android:dd1026c5cd5e4e0c573261',
    messagingSenderId: '777032316980',
    projectId: 'chatly-11c65',
    storageBucket: 'chatly-11c65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsagv6SX1y6EIiRtCBLuGl_Ne54nz6pEU',
    appId: '1:777032316980:ios:db7a007587f86361573261',
    messagingSenderId: '777032316980',
    projectId: 'chatly-11c65',
    storageBucket: 'chatly-11c65.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsagv6SX1y6EIiRtCBLuGl_Ne54nz6pEU',
    appId: '1:777032316980:ios:db7a007587f86361573261',
    messagingSenderId: '777032316980',
    projectId: 'chatly-11c65',
    storageBucket: 'chatly-11c65.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwHSqNFuSYHKPMd-JAUsIplPtcSioHm3k',
    appId: '1:777032316980:web:3a189ad18dbc5811573261',
    messagingSenderId: '777032316980',
    projectId: 'chatly-11c65',
    authDomain: 'chatly-11c65.firebaseapp.com',
    storageBucket: 'chatly-11c65.firebasestorage.app',
    measurementId: 'G-DE1R5RG7F4',
  );
}
